import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'  
import Header from "@/components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UniNotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} min-h-screen`}>
        <div className="h-[20%]">
      <Header />

      </div>
        <main className="flex flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}